### Variáveis
@url=http://localhost:3000


### Requisição GET
GET {{url}}


### Contatos
GET {{url}}/contatos

### 
GET {{url}}/contatos/4




### Requisição POST
POST {{url}}/contato
Content-Type: application/json

{
    "nome":"Joao",
    "email": "joao@gmail.com",
    "telefone": "44123451234"
}